# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('id',)},
        ),
    ]
